In [1]:
import pandas as pd
import geopandas as gpd
import json
import geojson

In [2]:
counties_df = gpd.read_file("counties.json", encoding="utf-8")
counties_df

,GEO_ID,STATE,COUNTY,NAME,LSAD,CENSUSAREA,geometry
0,0500000US01001,01,001,Autauga,County,594.436,"POLYGON ((-86.49677 32.34444, -86.71790 32.402..."
1,0500000US01009,01,009,Blount,County,644.776,"POLYGON ((-86.57780 33.76532, -86.75914 33.840..."
2,0500000US01017,01,017,Chambers,County,596.531,"POLYGON ((-85.18413 32.87053, -85.12342 32.772..."
3,0500000US01021,01,021,Chilton,County,692.854,"POLYGON ((-86.51734 33.02057, -86.51596 32.929..."
4,0500000US01033,01,033,Colbert,County,592.619,"POLYGON ((-88.13999 34.58170, -88.13925 34.587..."
...,...,...,...,...,...,...,...
3135,0500000US51001,51,001,Accomack,County,449.496,"MULTIPOLYGON (((-75.24227 38.02721, -75.29687 ..."
3136,0500000US51021,51,021,Bland,County,357.725,"POLYGON ((-81.22510 37.23487, -81.20477 37.243..."
3137,0500000US51027,51,027,Buchanan,County,502.763,"POLYGON ((-81.96830 37.53780, -81.92787 37.512..."
3138,0500000US51037,51,037,Charlotte,County,475.271,"POLYGON ((-78.44332 37.07940, -78.49303 36.891..."
3139,0500000US51041,51,041,Chesterfield,County,423.297,"POLYGON ((-77.85180 37.35487, -77.85515 37.418..."

In [3]:
info_df = pd.read_csv("BreweryProject2-RGbranch/countydemographicsv1.csv", encoding = "utf-8")
info_df

,fips_txt,Stabr,area_name,median_HHI_2019,bach_deg_pct_14to18,Latitude,Longitude
0,1001,AL,"Autauga County, AL",58233.0,27.7,32.53638,-86.644490
1,1003,AL,"Baldwin County, AL",59871.0,31.3,30.65922,-87.746067
2,1005,AL,"Barbour County, AL",35972.0,12.2,31.87067,-85.405456
3,1007,AL,"Bibb County, AL",47918.0,11.5,33.01589,-87.127148
4,1009,AL,"Blount County, AL",52902.0,12.6,33.97745,-86.567246
...,...,...,...,...,...,...,...
3135,56037,WY,"Sweetwater County, WY",80639.0,22.0,41.66034,-108.875676
3136,56039,WY,"Teton County, WY",98837.0,57.4,44.04932,-110.588102
3137,56041,WY,"Uinta County, WY",70756.0,15.4,41.28473,-110.558947
3138,56043,WY,"Washakie County, WY",55122.0,21.5,43.87883,-107.669052
3139,56045,WY,"Weston County, WY",59410.0,19.2,43.84621,-104.570020

In [4]:
ordered_counties = counties_df.sort_values(by=["GEO_ID"]).reset_index(drop = True)
ordered_counties

,GEO_ID,STATE,COUNTY,NAME,LSAD,CENSUSAREA,geometry
0,0500000US01001,01,001,Autauga,County,594.436,"POLYGON ((-86.49677 32.34444, -86.71790 32.402..."
1,0500000US01003,01,003,Baldwin,County,1589.784,"POLYGON ((-87.59893 30.99745, -87.59411 30.976..."
2,0500000US01005,01,005,Barbour,County,884.876,"POLYGON ((-85.05603 32.06305, -85.05021 32.024..."
3,0500000US01007,01,007,Bibb,County,622.582,"POLYGON ((-87.42120 32.87451, -87.42013 32.902..."
4,0500000US01009,01,009,Blount,County,644.776,"POLYGON ((-86.57780 33.76532, -86.75914 33.840..."
...,...,...,...,...,...,...,...
3135,0500000US56037,56,037,Sweetwater,County,10426.649,"POLYGON ((-110.04800 41.57802, -110.05371 42.2..."
3136,0500000US56039,56,039,Teton,County,3995.379,"POLYGON ((-111.04875 44.06040, -111.04875 44.0..."
3137,0500000US56041,56,041,Uinta,County,2081.264,"POLYGON ((-111.04640 41.57984, -110.06279 41.5..."
3138,0500000US56043,56,043,Washakie,County,2238.549,"POLYGON ((-108.55076 44.07940, -108.55056 44.1..."
3139,0500000US56045,56,045,Weston,County,2398.089,"POLYGON ((-104.05508 43.93653, -104.05510 43.8..."

In [5]:
useful_info_df = info_df[["median_HHI_2019", "bach_deg_pct_14to18"]]
useful_info_df

      median_HHI_2019  bach_deg_pct_14to18
0             58233.0                 27.7
1             59871.0                 31.3
2             35972.0                 12.2
3             47918.0                 11.5
4             52902.0                 12.6
...               ...                  ...
3135          80639.0                 22.0
3136          98837.0                 57.4
3137          70756.0                 15.4
3138          55122.0                 21.5
3139          59410.0                 19.2

[3140 rows x 2 columns]

In [6]:
final_county_df = pd.concat([useful_info_df, ordered_counties], axis = 1)
final_county_df

,median_HHI_2019,bach_deg_pct_14to18,GEO_ID,STATE,COUNTY,NAME,LSAD,CENSUSAREA,geometry
0,58233.0,27.7,0500000US01001,01,001,Autauga,County,594.436,"POLYGON ((-86.49677 32.34444, -86.71790 32.402..."
1,59871.0,31.3,0500000US01003,01,003,Baldwin,County,1589.784,"POLYGON ((-87.59893 30.99745, -87.59411 30.976..."
2,35972.0,12.2,0500000US01005,01,005,Barbour,County,884.876,"POLYGON ((-85.05603 32.06305, -85.05021 32.024..."
3,47918.0,11.5,0500000US01007,01,007,Bibb,County,622.582,"POLYGON ((-87.42120 32.87451, -87.42013 32.902..."
4,52902.0,12.6,0500000US01009,01,009,Blount,County,644.776,"POLYGON ((-86.57780 33.76532, -86.75914 33.840..."
...,...,...,...,...,...,...,...,...,...
3135,80639.0,22.0,0500000US56037,56,037,Sweetwater,County,10426.649,"POLYGON ((-110.04800 41.57802, -110.05371 42.2..."
3136,98837.0,57.4,0500000US56039,56,039,Teton,County,3995.379,"POLYGON ((-111.04875 44.06040, -111.04875 44.0..."
3137,70756.0,15.4,0500000US56041,56,041,Uinta,County,2081.264,"POLYGON ((-111.04640 41.57984, -110.06279 41.5..."
3138,55122.0,21.5,0500000US56043,56,043,Washakie,County,2238.549,"POLYGON ((-108.55076 44.07940, -108.55056 44.1..."
3139,59410.0,19.2,0500000US56045,56,045,Weston,County,2398.089,"POLYGON ((-104.05508 43.93653, -104.05510 43.8..."

In [7]:
final_county_gdf = gpd.GeoDataFrame(final_county_df)

In [8]:
final_county_gdf.to_file("final_counties.geojson", driver ='GeoJSON', encoding = "utf-8")